version: 1.0.00-RC2
name: Library
module:
    name: Library
    description: 'Allows the management of a catalogue from which items can be borrowed.'
    entryURL: manage_catalogue
    type: Additional
    active: 'Y'
    category: Learn
    version: 0.0.00
    author: 'Craig Rayner'
    url: 'https://www.craigrayner.com'
    actions:
        'Manage Catalogue':
            name: 'Manage Catalogue'
            precedence: 0
            category: Catalogue
            description: Control all items in the school library catalogue
            URLList: manage_catalogue,edit,loan_item,duplicate_item
            entryURL: manage_catalogue
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Browse The Library':
            name: 'Browse The Library'
            precedence: 0
            category: Catalogue
            description: Search and view all borrowable items maintained by the library.
            URLList: browse
            entryURL: browse
            entrySidebar: 'N'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'Y'
            defaultPermissionStudent: 'Y'
            defaultPermissionParent: 'Y'
            defaultPermissionSupport: 'Y'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'Y'
            categoryPermissionParent: 'Y'
            categoryPermissionOther: 'Y'
            permissions:
                - Administrator
                - Teacher
                - Parent
                - Student
                - 'Support Staff'
        'View Overdue Items':
            name: 'View Overdue Items'
            precedence: 0
            category: Reports
            description: 'View items which are on loan and have exceeded their due date.'
            URLList: overdue_item_report
            entryURL: overdue_item_report
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'Y'
            categoryPermissionParent: 'Y'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Borrowing Record':
            name: 'Borrowing Record'
            precedence: 0
            category: Reports
            description: 'View items borrowed by an individual.'
            URLList: report_borrow_record
            entryURL: report_borrow_record
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'Y'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'Y'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
                - Teacher
                - 'Support Staff'
        'Library Settings':
            name: 'Library Settings'
            precedence: 0
            category: Settings
            description: 'Change the core settings of a library.'
            URLList: settings
            entryURL: settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'Y'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
                - 'Support Staff'
        'Loan / Return Manager':
            name: 'Loan / Return Manager'
            precedence: 0
            category: Catalogue
            description: 'Lend and return items using a bar-code scanner.'
            URLList: quick_loan
            entryURL: quick_loan
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'Y'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
                - 'Support Staff'

events:
    'Overdue Loan Items':
        name: Overdue Loan Items
        action: 'Manage Catalogue'
        type: CLI
        scopes: ['All']
        active: 'Y'
    'Reserved Item Available':
        name: Reserved Item Available
        action: 'Manage Catalogue'
        type: Additional
        scopes: ['All']
        active: 'Y'
