SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE gibbonLibraryItem DROP FOREIGN KEY FK_7D8DF16EA18098BC;
ALTER TABLE gibbonLibraryItemEvent DROP FOREIGN KEY FK_91CB122520179A14;
DROP TABLE gibbonLibrary;
DROP TABLE gibbonLibraryItem;
DROP TABLE gibbonLibraryItemEvent;
SET FOREIGN_KEY_CHECKS = 1;
